spring:
  application:
    name: catchTable
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: test
    password: test1234
  security:
    user:
      name: user
      password: 1111
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false
    enabled: true

#  devtools:
#    restart:
#      enabled: true  # 애플리케이션 리스타트 활성화
#    livereload:
#      enabled: true  # LiveReload 활성화
  #  mvc:
#    static-path-pattern: /static/** # spring mvc 정적경로 변경

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
server:
  port: 8013
